
version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.12-bookworm"
    command: sleep infinity
    init: true
    tty: true
    user: vscode
    volumes:
      - ..:/workspaces/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # Cache Poetry dependencies for faster rebuilds
      - poetry-cache:/tmp/poetry_cache
    environment:
      # Python/Poetry configuration
      POETRY_VENV_IN_PROJECT: "1"
      POETRY_CACHE_DIR: "/tmp/poetry_cache"
      POETRY_NO_INTERACTION: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      
      # Azure development environment variables (override in .env file)
      AZURE_SEARCH_ENDPOINT: "${AZURE_SEARCH_ENDPOINT:-}"
      AZURE_SEARCH_API_KEY: "${AZURE_SEARCH_API_KEY:-}"
      AZURE_SEARCH_API_VERSION: "${AZURE_SEARCH_API_VERSION:-2023-11-01}"
      SEARCH_INDEX_NAME_QUESTIONS: "${SEARCH_INDEX_NAME_QUESTIONS:-questions}"
      SEARCH_SIMILARITY_THRESHOLD: "${SEARCH_SIMILARITY_THRESHOLD:-0.75}"
      AZURE_OPENAI_ENDPOINT: "${AZURE_OPENAI_ENDPOINT:-}"
      AZURE_OPENAI_API_KEY: "${AZURE_OPENAI_API_KEY:-}"
      AZURE_OPENAI_API_VERSION: "${AZURE_OPENAI_API_VERSION:-2024-02-01}"
      AZURE_OPENAI_MODEL_NAME: "${AZURE_OPENAI_MODEL_NAME:-gpt-4}"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "${APPLICATIONINSIGHTS_CONNECTION_STRING:-}"

volumes:
  poetry-cache:
